os: Visual Studio 2015
configuration: Release
install:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;C:\\ProgramData\\chocolatey\\bin;%PATH%"
  - choco install gitversion.portable -pre -y
  - choco install GitReleaseNotes.Portable
  - pip install codecov
before_build:
  - nuget restore
  - gitversion /l console /output buildserver
  - GitReleaseNotes . /AllTags /C breaking /O ReleaseNotes.md
build:
  project: Pegasus.sln
after_test:
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"nunit-console.exe" -targetargs:".\Pegasus.Tests\bin\%CONFIGURATION%\Pegasus.Tests.dll /noshadow /exclude=Performance" -filter:"+[Pegasus]* +[Pegasus.Common]* -[Pegasus]Pegasus.Program.* -[Pegasus]Pegasus.Parser.* -[Pegasus]Pegasus.Properties.*" -hideskipped:All -output:.\Pegasus.Tests\bin\%CONFIGURATION%\coverage.xml
  - codecov -X gcov -f ".\Pegasus.Tests\bin\%CONFIGURATION%\coverage.xml"
cache:
  - packages -> **\packages.config
artifacts:
  - path: 'ReleaseNotes.md'
  - path: 'Package\bin\**\*.nupkg'
  - path: 'Pegasus.Templates\bin\**\*.zip'
  - path: 'Pegasus.Package\bin\**\*.vsix'
  - path: 'Pegasus.Workbench\bin\%CONFIGURATION%'
    name: Pegasus.Workbench
    type: zip
deploy:
  provider: NuGet
  api_key:
    secure: 2tZ8tu75MkmhyIcFGzFZsukJx9WAfV94mMtIAnSlurGlGqKaUhG6n6fTimXiIQiB
  skip_symbols: false
  artifact: /.*\.nupkg/
skip_commits:
  files:
    - .gitattributes
    - .gitignore
    - CodeMaid.config
    - license.md
    - pegasus.gv
    - Pegasus.svg
