os: Visual Studio 2015
configuration: Release
install:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - choco install gitversion.portable -pre -y
  - pip install codecov
before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver
build:
  project: Pegasus.sln
after_test:
  - .\packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -register:user -target:"nunit-console.exe" -targetargs:".\Pegasus.Tests\bin\%CONFIGURATION%\Pegasus.Tests.dll /noshadow /exclude=Performance" -filter:"+[Pegasus]* +[Pegasus.Common]* -[Pegasus]Pegasus.Parser.* -[Pegasus]Pegasus.Properties.*" -hideskipped:All -output:.\Pegasus.Tests\bin\%CONFIGURATION%\coverage.xml
  - codecov -X gcov -f ".\Pegasus.Tests\bin\%CONFIGURATION%\coverage.xml"
cache:
  - packages -> **\packages.config
artifacts:
  - path: 'Package\bin\**\*.nupkg'
  - path: 'Pegasus.Package\bin\**\*.vsix'
